export const BUTTONS = {
  mainMenu: "\u2B05\uFE0F Asosiy menyu",
  back: "\u2B05\uFE0F Orqaga",
  account: "\uD83D\uDC64 Hisobim",
  topUp: "\uD83D\uDCB3 Hisobni to'ldirish",
  stopWork: "\uD83D\uDCF4 Ishni yakunlash",
  enableDriverMode: "\uD83D\uDE95 Haydovchi rejimini yoqish",
  becomeDriver: "\uD83D\uDE96 Haydovchi bo'lish",
  callTaxi: "\uD83D\uDE95 Taxi chaqirish",
  myOrders: "\u2116\uFE0F Mening elonlarim",
  sendPhone: "\uD83D\uDCF1 Telefon raqamni yuborish",
  sendLocation: "\uD83D\uDCCD Lokatsiyani yuborish",
  refreshLocation: "\uD83D\uDCCD Lokatsiyani yangilash",
  adminPanel: "\uD83D\uDEE0 Admin panel",
  activeUsers: "\uD83D\uDC65 Faol userlar",
  activeDrivers: "\uD83D\uDE95 Faol driverlar",
  blockedUsers: "\uD83D\uDEAB Botni bloklaganlar",
  broadcast: "\uD83D\uDCE3 Xabar yuborish",
};
